name: supabase_annotations_example
description: Example demonstrating how to use supabase_annotations package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: ^1.17.0
  supabase_annotations:
    path: ../


dev_dependencies:
  build_runner: ^2.4.8
  source_gen: ^1.2.7
