name: supabase_annotations
description: >-
  Code generator for Supabase/PostgreSQL database schemas from Dart classes. 
  Supports RLS policies, indexes, foreign keys, migration, and table partitioning.
version: 1.1.7
homepage: https://github.com/ahmtydn/supabase_annotations
repository: https://github.com/ahmtydn/supabase_annotations
issue_tracker: https://github.com/ahmtydn/supabase_annotations/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Core dependencies for annotation processing
  analyzer: ^8.1.1
  build: ^3.1.0
  collection: ^1.18.0
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  recase: ^4.1.0
  source_gen: ^3.0.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  test: ^1.25.2
  very_good_analysis: ^9.0.0

# Package metadata
topics:
  - supabase
  - postgresql
  - database
  - schema
  - code-generation

platforms:
  linux:
  macos:
  windows:
